name: Build a docker container

on:
  push:
    branches:
      - main

# see: https://github.com/marketplace/actions/build-and-push-docker-images
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/toolchaincdi:latest
            ghcr.io/${{ github.repository_owner }}/toolchaincdi:${{ github.sha }}
